[build]
  command = "php -v && cp -R ../assets public/assets && cp ../index.php public/index.php"
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"